import { TendrilDashboard, TendrilProcessViewer } from '@spacecorps/components-storybook/tendril';
import {
  dashboardFixture,
  processViewerFixture,
  type DashboardFixture,
} from '../../fixtures/dashboard.js';

const noop = () => {};

/** Deterministic stand-in for the tunnel QR code, which is generated by the host app. */
function TunnelQrPlaceholder() {
  // A fixed 7x7 bit pattern keeps the recording byte-comparable across runs.
  const pattern = [
    [1, 1, 1, 0, 1, 1, 1],
    [1, 0, 1, 0, 1, 0, 1],
    [1, 1, 1, 0, 1, 1, 1],
    [0, 0, 0, 1, 0, 0, 0],
    [1, 1, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 1, 1],
    [1, 1, 1, 0, 1, 1, 1],
  ];
  return (
    <div
      aria-label="Tunnel QR code"
      style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(7, 1fr)',
        gap: 2,
        width: 112,
        height: 112,
        padding: 8,
        background: '#ffffff',
        borderRadius: 6,
      }}
    >
      {pattern.flatMap((row, y) =>
        row.map((bit, x) => (
          <div key={`${y}-${x}`} style={{ background: bit ? '#0a0a0a' : 'transparent' }} />
        ))
      )}
    </div>
  );
}

/**
 * High-fidelity Tendril dashboard demo. Renders the real `TendrilDashboard` component with the
 * pipeline viewer in its Software Factory slot and a tunnel card, so the scripted recording can
 * drive the trend tabs, the Git Activity / Pull Requests tabs and the status counters.
 */
export default function TendrilDashboardDemo(props: Partial<DashboardFixture> = {}) {
  const merged = { ...dashboardFixture, ...props };

  return (
    <TendrilDashboard
      {...merged}
      eventHandler={noop}
      slots={{
        ProcessViewer: <TendrilProcessViewer {...processViewerFixture} eventHandler={noop} />,
        TunnelQr: <TunnelQrPlaceholder />,
      }}
    />
  );
}
